-- Autogenerated by migration tool on 2022-02-10 15:50:37

-- Resource: waf
CREATE TABLE IF NOT EXISTS "cloudflare_waf_package" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"ID" text,
	"Description" text,
	"Action" text,
	"Filter" jsonb,
	"CreatedOn" timestamp without time zone,
	"ModifiedOn" timestamp without time zone,
	"Paused" boolean,
	CONSTRAINT cloudflare_waf_package_pk PRIMARY KEY(cq_fetch_date,cq_id),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('cloudflare_waf_package');

-- Resource: zone
CREATE TABLE IF NOT EXISTS "cloudflare_zones" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"ID" text,
	"Name" text,
	"Account" text,
	"NameServers" text[],
	"Status" text,
	"CreatedOn" timestamp without time zone,
	"ModifiedOn" timestamp without time zone,
	"ActivatedOn" timestamp without time zone,
	"OwnerEmail" text,
	"OwnerName" text,
	"HostName" text,
	CONSTRAINT cloudflare_zones_pk PRIMARY KEY(cq_fetch_date,cq_id),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('cloudflare_zones');
CREATE TABLE IF NOT EXISTS "cloudflare_zone_waf_packages" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"ZoneID" uuid,
	"Name" text,
	"ID" bigint,
	"DetectionMode" text,
	CONSTRAINT cloudflare_zone_waf_packages_pk PRIMARY KEY(cq_fetch_date,cq_id),
	UNIQUE(cq_fetch_date,cq_id)
);
SELECT setup_tsdb_parent('cloudflare_zone_waf_packages');
