-- Autogenerated by migration tool on 2022-02-11 15:44:57

-- Resource: zone
DROP TABLE IF EXISTS cloudflare_zone_waf_packages;
DROP TABLE IF EXISTS cloudflare_zone_dns_records;
DROP TABLE IF EXISTS cloudflare_zones;
