-- Autogenerated by migration tool on 2022-02-09 16:31:22

-- Resource: zone
CREATE TABLE IF NOT EXISTS "cloudflare_zones" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"ID" text,
	"Name" text,
	"Account" text,
	"NameServers" text[],
	"Status" text,
	"CreatedOn" timestamp without time zone,
	"ModifiedOn" timestamp without time zone,
	"ActivatedOn" timestamp without time zone,
	"OwnerEmail" text,
	"OwnerName" text,
	"HostName" text,
	CONSTRAINT cloudflare_zones_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id)
);
