-- Autogenerated by migration tool on 2022-02-11 15:37:16

-- Resource: waf
DROP TABLE IF EXISTS cloudflare_waf_package;

-- Resource: zone
DROP TABLE IF EXISTS cloudflare_zone_waf_packages;
DROP TABLE IF EXISTS cloudflare_zone_dns_records;
DROP TABLE IF EXISTS cloudflare_zones;
