-- Autogenerated by migration tool on 2022-02-09 15:15:35

-- Resource: zone
CREATE TABLE IF NOT EXISTS "zones" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"ID" text,
	"Name" text,
	"Account" text,
	"NameServers" text[],
	CONSTRAINT zones_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id)
);
